lojaapp/urls.py
from django.urls import path
from.views import *

app_name = "lojaapp"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("all-products/", TodosProdutosView.as_view(), name="allproducts"),
    path("produto/<slug:slug>/", ProdutoDetalheView.as_view(), name="produtodetalhe"),
    path("addcarro-<int:pro_id>/", AddCarroView.as_view(), name="addcarro"),
    path("meu-carro/", MeuCarroView.as_view(), name="meucarro"),
    path("manipular-carro/<int:cp_id>/", ManipularCarroView.as_view(), name="manipularcarro"),
]

lojaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lojaapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lojaapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_completo = models.CharField(max_length=100)
    endereco = models.CharField(max_length=200, null=True, blank=True)
    data_cadastro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome_completo

# Creating class Categoria
class Categoria(models.Model):
    titulo = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, max_length=100)

    def __str__(self):
        return self.titulo

# Creating class Produto
class Produto(models.Model):
    titulo = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, max_length=100)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    imagem = models.ImageField(upload_to="produtos")
    preco_mercado = models.PositiveIntegerField()
    venda = models.PositiveIntegerField()
    descricao = models.TextField()
    garantia = models.CharField(max_length=100, null=True, blank=True)
    return_devolucao = models.CharField(max_length=300, null=True, blank=True)
    visualizacao = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.titulo

# Creating class Carro
class Carro(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    criado_em = models.DateField(auto_now_add=True)

    def __str__(self):
        return "Carro" + str(self.id)

# Creating class CarroProduto
class CarroProduto(models.Model):
    carro = models.ForeignKey(Carro, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    avaliacao_produto = models.PositiveIntegerField()
    quantidade = models.PositiveIntegerField()
    sub_total = models.PositiveIntegerField()

    def __str__(self):
        return "Carro" + str(self.carro.id) + "CarroProduto" + str(self.id)

PEDIDO_STATUS = (
    ("Pedido recebido", "Pedido recebido"),
    ("Pedido sendo processado", "Pedido sendo processado"),
    ("Pedido a caminho", "Pedido a caminho"),
    ("Pedido entregue", "Pedido entregue"),
    ("Pedido cancelado", "Pedido cancelado"),
)

class Pedido_order(models.Model):
    carro = models.OneToOneField(Carro, on_delete=models.CASCADE)
    ordenado_por = models.CharField(max_length=100)
    endereco_envio = models.CharField(max_length=200)
    telefone = models.CharField(max_length=20)
    email = models.EmailField(null=True, blank=True)
    endereco_envio = models.CharField(max_length=200)
    sub_total = models.PositiveIntegerField
    desconto = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    pedido_status = models.CharField(max_length=50, choices=PEDIDO_STATUS)
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Pedido_order: " + str(self.id)

lojaapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView
from .models import *

class HomeView(TemplateView):
    template_name = "home.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['produto_list'] = Produto.objects.all()
        return context

class TodosProdutosView(TemplateView):
    template_name = "allproducts.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['todascategorias'] = Categoria.objects.all().order_by('-id')
        return context    

class ProdutoDetalheView(TemplateView):
    template_name = "produtodetalhe.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        url_slug = kwargs['slug']
        produto = Produto.objects.get(slug=url_slug)
        produto.visualizacao += 1
        produto.save()
        context['produto'] = produto
        return context

class AddCarroView(TemplateView):
    template_name = "productAdded.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        produto_id = self.kwargs['pro_id']
        produto_obj = Produto.objects.get(id=produto_id)
        carro_id = self.request.session.get("carro_id", None)
        if carro_id:
            carro_obj = Carro.objects.get(id=carro_id)
            produto_no_carro = carro_obj.carroproduto_set.filter(produto=produto_obj)
            if produto_no_carro.exists():
                carroproduto = produto_no_carro.last()
                carroproduto.quantidade += 1
                carroproduto.sub_total += produto_obj.venda
                carroproduto.save()
                carro_obj.total += produto_obj.venda
                carro_obj.save()

            else:
                carroproduto = CarroProduto.objects.create(carro=carro_obj, produto=produto_obj, avaliacao_produto=produto_obj.venda, quantidade=1, sub_total=produto_obj.venda)
                carro_obj.total += produto_obj.venda
                carro_obj.save()
        
        else:
            carro_obj = Carro.objects.create(total=0)
            self.request.session['carro_id'] = carro_obj.id
            carroproduto = CarroProduto.objects.create(carro=carro_obj, produto=produto_obj, avaliacao_produto=produto_obj.venda, quantidade=1, sub_total=produto_obj.venda)
            carro_obj.total += produto_obj.venda
            carro_obj.save()
        return context


class ManipularCarroView(View):
    def get(self, request, *args,  **kwargs):
        cp_id = self.kwargs["cp_id"]
        acao = request.GET.get("acao")
        cp_obj = CarroProduto.objects.get(id=cp_id)
        carro_obj = cp_obj.carro

        if acao == "inc":
            cp_obj.quantidade += 1
            cp_obj.sub_total += cp_obj.avaliacao_produto
            cp_obj.save()
            carro_obj.total += cp_obj.avaliacao_produto
            carro_obj.save()
        elif acao == "dcr":
            cp_obj.quantidade -= 1
            cp_obj.sub_total -= cp_obj.avaliacao_produto
            cp_obj.save()
            carro_obj.total -= cp_obj.avaliacao_produto
            carro_obj.save()

            if cp_obj.quantidade == 0:
                cp_obj.delete()
                
        elif acao == "rmv":
            carro_obj.total -= cp_obj.sub_total
            carro_obj.save()
            cp_obj.delete()
        else:
            pass
        return redirect("lojaapp:meucarro")



class MeuCarroView(TemplateView):
    template_name = "meucarro.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        carro_id = self.request.session.get("carro_id", None)
        if carro_id:
            carro = Carro.objects.get(id=carro_id)
        else:
            carro = None
        context['carro'] = carro
        return context

templates/allproducts.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <h1 class="text-center">Produtos por categoria</h1>

  {% for cat in todascategorias %}
    <h1 class="mt-5">{{cat.titulo}}</h1>

    <div class="row mt-3">
      {% for p in cat.produto_set.all %}
      <div
        class="d-flex flex-column col-md-4 shadow p-5 rounded m-5 overflow-hidden"
      >
        <h4 class="text-center">
          <a
            href="{% url 'lojaapp:produtodetalhe' p.slug %}"
            style="text-decoration: none"
            class="text-black"
            >{{p.titulo}}
          </a>
        </h4>
        <img
          src="{{p.imagem.url}}"
          class="img-fluid w-100"
          alt="{{p.titulo}}"
          style="height: 150px; object-fit: contain"
        />
        <div class="d-flex justify-content-between">
          <p class="mt-3">A partir de R$ {{p.venda}},00</p>
          
          
          <a 
            href="{% url 'lojaapp:addcarro' p.id%}" 
            class="btn btn-success align-self-center"
            style="height: 40px; width: 100px; font-size: 15px"
          >
            Comprar
          </a>
        </div>
      </div>
      {% endfor%}
    </div>
  {% endfor%}
</div>
{% endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="/media/Apple-logo.ico" rel="icon" type="image/x-icon" />
    <title>Apple Store</title>

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <link
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div
      class="d-flex flex-row align-items-center justify-content-around  px-5" style="background-color: #F5F5F7;"
    >
      <a href="{% url 'lojaapp:home' %}">
        <svg height="44" viewBox="0 0 14 44" width="14" ><path d="m13.0729 17.6825a3.61 3.61 0 0 0 -1.7248 3.0365 3.5132 3.5132 0 0 0 2.1379 3.2223 8.394 8.394 0 0 1 -1.0948 2.2618c-.6816.9812-1.3943 1.9623-2.4787 1.9623s-1.3633-.63-2.613-.63c-1.2187 0-1.6525.6507-2.644.6507s-1.6834-.9089-2.4787-2.0243a9.7842 9.7842 0 0 1 -1.6628-5.2776c0-3.0984 2.014-4.7405 3.9969-4.7405 1.0535 0 1.9314.6919 2.5924.6919.63 0 1.6112-.7333 2.8092-.7333a3.7579 3.7579 0 0 1 3.1604 1.5802zm-3.7284-2.8918a3.5615 3.5615 0 0 0 .8469-2.22 1.5353 1.5353 0 0 0 -.031-.32 3.5686 3.5686 0 0 0 -2.3445 1.2084 3.4629 3.4629 0 0 0 -.8779 2.1585 1.419 1.419 0 0 0 .031.2892 1.19 1.19 0 0 0 .2169.0207 3.0935 3.0935 0 0 0 2.1586-1.1368z"></path></svg>
      </a>

      <div class="gap-4 d-flex ">
        <a href="{% url 'lojaapp:allproducts' %}"  style="color: #313131;">Categorias</a>
      </div>


      <a href="{% url 'lojaapp:meucarro' %}" class="text-white" >
        <i class="fas fa-shopping-cart"><svg height="44" viewBox="0 0 14 44" width="14" xmlns="http://www.w3.org/2000/svg"><path d="m11.3535 16.0283h-1.0205a3.4229 3.4229 0 0 0 -3.333-2.9648 3.4229 3.4229 0 0 0 -3.333 2.9648h-1.02a2.1184 2.1184 0 0 0 -2.117 2.1162v7.7155a2.1186 2.1186 0 0 0 2.1162 2.1167h8.707a2.1186 2.1186 0 0 0 2.1168-2.1167v-7.7155a2.1184 2.1184 0 0 0 -2.1165-2.1162zm-4.3535-1.8652a2.3169 2.3169 0 0 1 2.2222 1.8652h-4.4444a2.3169 2.3169 0 0 1 2.2222-1.8652zm5.37 11.6969a1.0182 1.0182 0 0 1 -1.0166 1.0171h-8.7069a1.0182 1.0182 0 0 1 -1.0165-1.0171v-7.7155a1.0178 1.0178 0 0 1 1.0166-1.0166h8.707a1.0178 1.0178 0 0 1 1.0164 1.0166z"></path></svg></i>
      </a>
    </div>
    {% block content%} {% endblock %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %} {% block content %}
<div class="container d-flex">
  <div class="row mt-3">
    {% for p in produto_list %}
    <div class="col-md-4">
      <div class=" shadow p-3 mb-5 bg-body-tertiary rounded w-100 p-5 m-4 col-md-4 overflow-hidden">
        <h4 class="text-left">
          <a href="{% url 'lojaapp:produtodetalhe' p.slug %}" class="text-black" style="text-decoration: none">{{p.titulo}} </a>
        </h4>
        <img
          style="height: 150px; object-fit: contain"
          class="img-fluid w-100"
          src="{{p.imagem.url}}"
          alt=""
        />
        <div class="d-flex justify-content-between">
          <p class="mt-3">A partir de R$ {{p.venda}}</p>
          <a href="{% url 'lojaapp:addcarro' p.id%}" class="btn btn-success px-2 h-25 align-self-center">
            Comprar
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

templates/meucarro.html
{% extends 'base.html' %} {% block content%}

<div class="container">
  <div class=" w-100">
    <h4>Seu carrinho</h4>
    <table class="table" style="text-align: center;">
      <thead>
        <tr>
          <th class="text-center">Incrementar</th>
          <th class="text-center">Decrementar</th>
          <th class="text-center">Nome</th>
          <th class="text-center">Qtd</th>
          <th class="text-center">Total</th>
        </tr>
      </thead>
      <tbody>
        {% for cp in carro.carroproduto_set.all %}
        <tr>
          <td>
            <a
              href="{% url 'lojaapp:manipularcarro' cp.id %}?acao=inc"
              class="btn btn-success"
              >+
            </a>
          </td>
          <td>
            <a
              href="{% url 'lojaapp:manipularcarro' cp.id %}?acao=dcr"
              class="btn btn-danger"
              >-</a
            >
          </td>
          <td>{{ cp.produto.titulo }}</td>
          <td>{{ cp.quantidade}}</td>
          <td>R$ {{ cp.sub_total }},00</td>
        </tr>
        {% endfor %}
        <tr>
          <th colspan="5" class="text-center">Total: R$ {{carro.total}},00</th>
        </tr>
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

templates/processar.html
{% extends 'base.html' %} {% block content %}
<div class="container p-3">
  <div class="row">
    <div class="col-md-6">
      <h3>Itens do carrinho</h3>
      <a
        href="{% url 'lojaapp:meucarro' %}?acao=rmv"
        class="btn btn-dark text-white"
        >Atualizar carrinho
      </a>
      <table class="table">
        <thead>
          <tr>
            <th>Codigo</th>
            <th>Produto</th>
            <th>Avaliacao</th>
            <th>Quantidade</th>
            <th>Subtotal</th>
            <th>Acao</th>
          </tr>
        </thead>
        <tbody>
          {% for cp in carro.carroproduto_set.all %}

          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ cp.produto.titulo }}</td>
            <td>{{ cp.avaliacao_produto }}</td>
            <td>{{ cp.quantidade}}</td>
            <td>{{ cp.sub_total }}</td>
          </tr>
          {% endfor %}
        </tbody>
        <tr>
          <th colspan="5" class="text-right">Valor total</th>
          <th>R$ {{carro.total}}</th>
        </tr>
      </table>
    </div>
    <div class="col-md-6">
      <h3>Detalhes da compra</h3>
      <form action=""></form>
    </div>
  </div>
</div>

{% endblock %}

templates/productAdded.html
{% extends 'base.html' %} {% block title %}Carro{% endblock %} 

{% block content %}
<div class="container fw-bold fs-1 p-3 text-info">Carro atualizado</div>
{% endblock content %}

templates/produtodetalhe.html
{% extends 'base.html' %} {% block title %} {{produto.titulo}} {% endblock %}
{%block content %}

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <img
        width="380px"
        src="{{produto.imagem.url}}"
        alt=""
        class="img-fluid"
      />
    </div>
    <div class="col-md-6 text-left">
      <h3>{{produto.titulo}}</h3>
      <div class="mt-3 text-danger">
        <p>Garantia: {{produto.garantia}}</p>
      </div>
      <h3>
        <strong>Preço</strong>: R$ {{produto.venda}},00
      </h3>
      <a href="{% url 'lojaapp:addcarro' produto.id%}" class="btn btn-success px-2 justify-content-center align-content-center">
        Comprar
      </a>
      <h4>Descrição: {{produto.descricao}}</h4>
    </div>
  </div>
</div>
{% endblock%}

templates/todosprodutos.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <h1 class="text-center">Produtos por categoria</h1>

  {% for cat in todascategorias %}
    <h1 class="mt-5">{{cat.titulo}}</h1>

    <div class="row mt-3">
      {% for p in cat.produto_set.all %}
      <div
        class="col-md-auto shadow p-5 bg-body-tertiary rounded m-5"
      >
        <div>
          <h4 class="text-center">
            <a
              href="{% url 'lojaapp:produtodetalhe' p.slug %}"
              style="text-decoration: none"
              class="text-black"
              >{{p.titulo}}
            </a>
          </h4>
          <img
            src="{{p.imagem.url}}"
            class="img-fluid"
            alt=""
            style="height: 150px; object-fit: cover"
          />
          <p class="mt-3">Por: R$ {{p.venda}}</p>
          <a href="#" class="btn btn-success">Comprar</a>
        </div>
      </div>
      {% endfor%}
    </div>
  {% endfor%}
</div>
{% endblock%}